### ISSUE TITLE
Regarding relative loss

### ISSUE THREAD

**Issue by FransHk** [ZPDu/Redesigning-Multi-Scale-Neural-Network-for-Crowd-Counting#3]
Has the relative loss been implemented yet? It is currently commented out and the function is not available. Thanks!

**Comment by ZPDu** [comment]
Hi, thanks for the reminder. I will update the loss this week

**Comment by FransHk** [comment]
Thanks!

**Comment by lowdewijk** [comment]
That would be great!

**Comment by ZPDu** [comment]
hey guys, the loss is uploaded. A little late because I rewrote it. Hope it'll be helpful

**Comment by FransHk** [comment]
Thank you very much for adding this :)

**Comment by lowdewijk** [comment]
Awesome. Much appreciated! :)
